import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-order',
  templateUrl: './order.component.html',
  styleUrls: ['./order.component.css']
})
export class OrderComponent implements OnInit {
  public customers: any = [
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '12.05.24',
      time: '10:00',
      currency: 10000,
      amount: 1,
      state: 'Доставлен',
      price: 10000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '12.05.24',
      time: '10:00',
      currency: 5000,
      amount: 4,
      state: 'Новый',
      price: 20000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '12.05.24',
      time: '10:00',
      currency: 10000,
      amount: 3,
      state: 'Оплачен',
      price: 30000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '15.01.24',
      time: '18:00',
      currency: 10000,
      amount: 3,
      state: 'Оплачен',
      price: 30000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '12.05.24',
      time: '10:00',
      currency: 10000,
      amount: 1,
      state: 'Доставлен',
      price: 10000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '12.05.24',
      time: '10:00',
      currency: 5000,
      amount: 4,
      state: 'Новый',
      price: 20000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '12.05.24',
      time: '10:00',
      currency: 10000,
      amount: 3,
      state: 'Оплачен',
      price: 30000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '15.01.24',
      time: '18:00',
      currency: 10000,
      amount: 3,
      state: 'Оплачен',
      price: 30000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '12.05.24',
      time: '10:00',
      currency: 10000,
      amount: 1,
      state: 'Доставлен',
      price: 10000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '12.05.24',
      time: '10:00',
      currency: 5000,
      amount: 4,
      state: 'Новый',
      price: 20000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '12.05.24',
      time: '10:00',
      currency: 10000,
      amount: 3,
      state: 'Оплачен',
      price: 30000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '15.01.24',
      time: '18:00',
      currency: 10000,
      amount: 3,
      state: 'Оплачен',
      price: 30000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '12.05.24',
      time: '10:00',
      currency: 10000,
      amount: 1,
      state: 'Доставлен',
      price: 10000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '12.05.24',
      time: '10:00',
      currency: 5000,
      amount: 4,
      state: 'Новый',
      price: 20000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '12.05.24',
      time: '10:00',
      currency: 10000,
      amount: 3,
      state: 'Оплачен',
      price: 30000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '15.01.24',
      time: '18:00',
      currency: 10000,
      amount: 3,
      state: 'Оплачен',
      price: 30000,
    },    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '12.05.24',
      time: '10:00',
      currency: 10000,
      amount: 1,
      state: 'Доставлен',
      price: 10000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '12.05.24',
      time: '10:00',
      currency: 5000,
      amount: 4,
      state: 'Новый',
      price: 20000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '12.05.24',
      time: '10:00',
      currency: 10000,
      amount: 3,
      state: 'Оплачен',
      price: 30000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '15.01.24',
      time: '18:00',
      currency: 10000,
      amount: 3,
      state: 'Оплачен',
      price: 30000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '12.05.24',
      time: '10:00',
      currency: 10000,
      amount: 1,
      state: 'Доставлен',
      price: 10000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '12.05.24',
      time: '10:00',
      currency: 5000,
      amount: 4,
      state: 'Новый',
      price: 20000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '12.05.24',
      time: '10:00',
      currency: 10000,
      amount: 3,
      state: 'Оплачен',
      price: 30000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '15.01.24',
      time: '18:00',
      currency: 10000,
      amount: 3,
      state: 'Оплачен',
      price: 30000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '12.05.24',
      time: '10:00',
      currency: 10000,
      amount: 1,
      state: 'Доставлен',
      price: 10000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '12.05.24',
      time: '10:00',
      currency: 5000,
      amount: 4,
      state: 'Новый',
      price: 20000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '12.05.24',
      time: '10:00',
      currency: 10000,
      amount: 3,
      state: 'Оплачен',
      price: 30000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '15.01.24',
      time: '18:00',
      currency: 10000,
      amount: 3,
      state: 'Оплачен',
      price: 30000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '12.05.24',
      time: '10:00',
      currency: 10000,
      amount: 1,
      state: 'Доставлен',
      price: 10000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '12.05.24',
      time: '10:00',
      currency: 5000,
      amount: 4,
      state: 'Новый',
      price: 20000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '12.05.24',
      time: '10:00',
      currency: 10000,
      amount: 3,
      state: 'Оплачен',
      price: 30000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '15.01.24',
      time: '18:00',
      currency: 10000,
      amount: 3,
      state: 'Оплачен',
      price: 30000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '12.05.24',
      time: '10:00',
      currency: 10000,
      amount: 1,
      state: 'Доставлен',
      price: 10000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '12.05.24',
      time: '10:00',
      currency: 5000,
      amount: 4,
      state: 'Новый',
      price: 20000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '12.05.24',
      time: '10:00',
      currency: 10000,
      amount: 3,
      state: 'Оплачен',
      price: 30000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '15.01.24',
      time: '18:00',
      currency: 10000,
      amount: 3,
      state: 'Оплачен',
      price: 30000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '12.05.24',
      time: '10:00',
      currency: 10000,
      amount: 1,
      state: 'Доставлен',
      price: 10000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '12.05.24',
      time: '10:00',
      currency: 5000,
      amount: 4,
      state: 'Новый',
      price: 20000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '12.05.24',
      time: '10:00',
      currency: 10000,
      amount: 3,
      state: 'Оплачен',
      price: 30000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '15.01.24',
      time: '18:00',
      currency: 10000,
      amount: 3,
      state: 'Оплачен',
      price: 30000,
    },

  ]
  constructor() { }

  ngOnInit(): void {
  }

}
