import { Component, OnDestroy, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { Subject, map, takeUntil } from 'rxjs';
import { ApiOrderService } from 'src/app/core';
import { LoaderService } from 'src/app/core/services/loader.service';
import { IOrder } from 'src/app/interfaces/orders-payments';

@Component({
  selector: 'app-order',
  templateUrl: './order.component.html',
  styleUrls: ['./order.component.css'],
})
export class OrderComponent implements OnInit, OnDestroy {
  public destroy$ = new Subject<void>();
  public customers: any = [
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '12.05.24',
      time: '10:00',
      currency: 10000,
      amount: 1,
      state: 'Доставлен',
      price: 10000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '12.05.24',
      time: '10:00',
      currency: 5000,
      amount: 4,
      state: 'Новый',
      price: 20000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '12.05.24',
      time: '10:00',
      currency: 10000,
      amount: 3,
      state: 'Оплачен',
      price: 30000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '15.01.24',
      time: '18:00',
      currency: 10000,
      amount: 3,
      state: 'Оплачен',
      price: 30000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '12.05.24',
      time: '10:00',
      currency: 10000,
      amount: 1,
      state: 'Доставлен',
      price: 10000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '12.05.24',
      time: '10:00',
      currency: 5000,
      amount: 4,
      state: 'Новый',
      price: 20000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '12.05.24',
      time: '10:00',
      currency: 10000,
      amount: 3,
      state: 'Оплачен',
      price: 30000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '15.01.24',
      time: '18:00',
      currency: 10000,
      amount: 3,
      state: 'Оплачен',
      price: 30000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '12.05.24',
      time: '10:00',
      currency: 10000,
      amount: 1,
      state: 'Доставлен',
      price: 10000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '12.05.24',
      time: '10:00',
      currency: 5000,
      amount: 4,
      state: 'Новый',
      price: 20000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '12.05.24',
      time: '10:00',
      currency: 10000,
      amount: 3,
      state: 'Оплачен',
      price: 30000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '15.01.24',
      time: '18:00',
      currency: 10000,
      amount: 3,
      state: 'Оплачен',
      price: 30000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '12.05.24',
      time: '10:00',
      currency: 10000,
      amount: 1,
      state: 'Доставлен',
      price: 10000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '12.05.24',
      time: '10:00',
      currency: 5000,
      amount: 4,
      state: 'Новый',
      price: 20000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '12.05.24',
      time: '10:00',
      currency: 10000,
      amount: 3,
      state: 'Оплачен',
      price: 30000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '15.01.24',
      time: '18:00',
      currency: 10000,
      amount: 3,
      state: 'Оплачен',
      price: 30000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '12.05.24',
      time: '10:00',
      currency: 10000,
      amount: 1,
      state: 'Доставлен',
      price: 10000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '12.05.24',
      time: '10:00',
      currency: 5000,
      amount: 4,
      state: 'Новый',
      price: 20000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '12.05.24',
      time: '10:00',
      currency: 10000,
      amount: 3,
      state: 'Оплачен',
      price: 30000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '15.01.24',
      time: '18:00',
      currency: 10000,
      amount: 3,
      state: 'Оплачен',
      price: 30000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '12.05.24',
      time: '10:00',
      currency: 10000,
      amount: 1,
      state: 'Доставлен',
      price: 10000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '12.05.24',
      time: '10:00',
      currency: 5000,
      amount: 4,
      state: 'Новый',
      price: 20000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '12.05.24',
      time: '10:00',
      currency: 10000,
      amount: 3,
      state: 'Оплачен',
      price: 30000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '15.01.24',
      time: '18:00',
      currency: 10000,
      amount: 3,
      state: 'Оплачен',
      price: 30000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '12.05.24',
      time: '10:00',
      currency: 10000,
      amount: 1,
      state: 'Доставлен',
      price: 10000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '12.05.24',
      time: '10:00',
      currency: 5000,
      amount: 4,
      state: 'Новый',
      price: 20000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '12.05.24',
      time: '10:00',
      currency: 10000,
      amount: 3,
      state: 'Оплачен',
      price: 30000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '15.01.24',
      time: '18:00',
      currency: 10000,
      amount: 3,
      state: 'Оплачен',
      price: 30000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '12.05.24',
      time: '10:00',
      currency: 10000,
      amount: 1,
      state: 'Доставлен',
      price: 10000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '12.05.24',
      time: '10:00',
      currency: 5000,
      amount: 4,
      state: 'Новый',
      price: 20000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '12.05.24',
      time: '10:00',
      currency: 10000,
      amount: 3,
      state: 'Оплачен',
      price: 30000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '15.01.24',
      time: '18:00',
      currency: 10000,
      amount: 3,
      state: 'Оплачен',
      price: 30000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '12.05.24',
      time: '10:00',
      currency: 10000,
      amount: 1,
      state: 'Доставлен',
      price: 10000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '12.05.24',
      time: '10:00',
      currency: 5000,
      amount: 4,
      state: 'Новый',
      price: 20000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '12.05.24',
      time: '10:00',
      currency: 10000,
      amount: 3,
      state: 'Оплачен',
      price: 30000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '15.01.24',
      time: '18:00',
      currency: 10000,
      amount: 3,
      state: 'Оплачен',
      price: 30000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '12.05.24',
      time: '10:00',
      currency: 10000,
      amount: 1,
      state: 'Доставлен',
      price: 10000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '12.05.24',
      time: '10:00',
      currency: 5000,
      amount: 4,
      state: 'Новый',
      price: 20000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '12.05.24',
      time: '10:00',
      currency: 10000,
      amount: 3,
      state: 'Оплачен',
      price: 30000,
    },
    {
      img: '',
      title: 'Диван Foster',
      color: 'black',
      date: '15.01.24',
      time: '18:00',
      currency: 10000,
      amount: 3,
      state: 'Оплачен',
      price: 30000,
    },
  ];
  public orderId = 0;
  public order: IOrder = {} as IOrder;
  constructor(
    private loader: LoaderService,
    private orderApi: ApiOrderService,
    private activeRout: ActivatedRoute
  ) {}

  ngOnInit(): void {
    this.loader.loaded = false;
    this.activeRout.paramMap
      .pipe(takeUntil(this.destroy$))
      .subscribe((resp) => (this.orderId = Number(resp.get('id'))));

    this.orderApi
      .getOrders()
      .pipe(
        map((resp) => {
          this.order = resp.filter((item) => item.id === this.orderId)[0];
          console.log(this.order);
        }),
        takeUntil(this.destroy$)
      )
      .subscribe();
  }
  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
  }
}
